#!/bin/sh /etc/rc.common

START=95
STOP=05
USE_PROCD=1

PROG=/usr/bin/leoxgpon
PIDFILE=/var/run/leoxgpon.pid

start_service() {
	local port interval host no_db

	config_load leoxgpon
	config_get port    main http_port   9101
	config_get host    main http_host   '0.0.0.0'
	config_get interval main db_interval 60
	config_get_bool no_db main db_enabled 1

	local db_flag=""
	[ "$no_db" = "0" ] && db_flag="--no-db"

	procd_open_instance
	procd_set_param command python3 "$PROG" \
		--port "$port" \
		--host "$host" \
		--interval "$interval" \
		$db_flag
	procd_set_param pidfile "$PIDFILE"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger leoxgpon
}

reload_service() {
	stop
	start
}
